<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Home extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
    }

    public function index()
    {
		$this->load->view('home');
        
    } 
    public function login()
    {
        $this->load->view('login');
    }
    public function homeAdmin(){
        if(!$this->session->userdata('logined') || $this->session->userdata('logined') != true)
        {
            redirect('/');
        }

        $this->load->view('admin/home');
    }
    public function homeUser(){
        if(!$this->session->userdata('logined') || $this->session->userdata('logined') != true)
        {
            redirect('/');
        }

        $this->load->view('user/home');
    }
    public function about(){
        $this->load->view('about');
    }
    public function aboutUser(){
        $this->load->view('user/about');
    }
    public function contact(){
        $this->load->view('contact');
    }
    public function contactUser(){
        $this->load->view('user/contact');
    }
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */