<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Login extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('prawedding_model');
        $this->load->model('member_model');
    }

    public function index()
    {
		
		if(!$this->input->post()) //jika tidak ada input data post maka akan ke halaman login
		{
			$this->load->view('login');
		}
		else
		{
			$cek_loginAdmin = $this->prawedding_model->cek_loginAdmin(
				$this->input->post('username'),
				$this->input->post('password')
				);
			$cek_loginMember = $this->member_model->cek_loginMember(
				$this->input->post('username'),
				$this->input->post('password')
				);
			if(!empty($cek_loginAdmin))
			{
				$this->session->set_userdata('username',$cek_loginAdmin->username);
				$this->session->set_userdata('logined',true);				
				redirect("home/homeAdmin");
			}
			else if(!empty($cek_loginMember))
			{
				$this->session->set_userdata('username',$cek_loginMember->username);
				$this->session->set_userdata('logined',true);				
				redirect("home/homeUser");
			}
			else 
			{
				redirect("/");
			}
		}
        
    } 
    public function registrasi(){
        $this->load->view('user/registrasi');
    }
     
	
	public function logout()
    {
		$this->session->unset_userdata('logined');//hapus session userdata
		redirect("/");
    } 
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */